object DepVersion {
    const val buildGradleVersion = "7.0.3"
    const val firebaseCrashAnalyticGradleVersion = "2.7.1"
    const val googleServicesVersion =  "4.3.8"
    const val kotlinVersion = "1.6.10"

    const val appcompatVersion = "1.3.1"
    const val coreKtxVersion = "1.6.0"
    const val materialVersion = "1.4.0"
    const val recyclerViewVersion = "1.2.1"
    const val activityVersion = "1.4.0"
    const val fragmentVersion = "1.4.0"
    const val constraintLayoutVersion = "2.1.1"
    const val cardViewVersion = "1.0.0"
    const val lifecycleVersion = "2.4.0"
    const val preferenceVersion = "1.1.1"
    const val retrofitVersion = "2.9.0"
    const val hiltVersion = "2.39.1"
    const val timberVersion = "5.0.1"
    const val roomVersion = "2.3.0"
    const val navigationVersion = "2.3.5"
    const val navigationSafeArgsVersion = "2.3.5"
    const val coroutinesVersion = "1.5.1"

    const val espressoVersion = "3.4.0"
    const val junitVersion = "4.13.2"
    const val junitExtVersion = "1.1.3"
}